apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kubeguard-pvc
  namespace: kubeguard
  labels:
    app: kubeguard-prediction-service
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
