apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kubeguard-prediction-service
  namespace: kubeguard
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: kubeguard-prediction-service
  endpoints:
  - port: http
    path: /metrics
    interval: 15s
