apiVersion: v1
kind: Service
metadata:
  name: kubeguard-prediction-service
  namespace: kubeguard
  labels:
    app: kubeguard-prediction-service
spec:
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: kubeguard-prediction-service
