apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kubeguard.fullname" . }}-config
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "kubeguard.labels" . | nindent 4 }}
data:
  PROMETHEUS_URL: {{ .Values.prometheus.url | quote }}
  MONITOR_NAMESPACES: {{ .Values.monitoring.namespaces | quote }}
  MONITOR_INTERVAL_SECONDS: {{ .Values.monitoring.intervalSeconds | quote }}
